---
version: "2.1"
services:
    web:
        build: .
        ports:
            - 8080:80
        volumes:
            - ${PWD}/app:/usr/src/myapp
    postgres:
        container_name: postgres
        image: postgres:9.6-alpine
        ports:
            - 5432:5432
        volumes:
            - /var/lib/postgresql/data
            - ${PWD}/sql:/docker-entrypoint-initdb.d
        healthcheck:
            test: psql --username app -c "SELECT COUNT(1) FROM pg_catalog.pg_roles;"
            interval: 30s
            timeout: 10s
            retries: 3
        environment:
            - SERVICE_NAME=app
            - POSTGRES_USER=app
            - POSTGRES_PASSWORD=app

    redis:
        image: redis:3-alpine
        ports:
            - 6379:6379
